<a href="https://colab.research.google.com/github/Bharat-Moorthy/MLAI---Paathsalaassignments/blob/main/BBC_ML_model_with_BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

Inputting the dataset

In [2]:
news=pd.read_csv("/content/BBC News.csv")

In [3]:
news

ArticleId                                               Text  \
0          1833  worldcom ex-boss launches defence lawyers defe...   
1           154  german business confidence slides german busin...   
2          1101  bbc poll indicates economic gloom citizens in ...   
3          1976  lifestyle  governs mobile choice  faster  bett...   
4           917  enron bosses in $168m payout eighteen former e...   
...         ...                                                ...   
1485        857  double eviction from big brother model caprice...   
1486        325  dj double act revamp chart show dj duo jk and ...   
1487       1590  weak dollar hits reuters revenues at media gro...   
1488       1587  apple ipod family expands market apple has exp...   
1489        538  santy worm makes unwelcome visit thousands of ...   

           Category  
0          business  
1          business  
2          business  
3              tech  
4          business  
...             ...  
1485  entertainment  
1486  entertainment  
1487       business  
1488           tech  
1489           tech  

[1490 rows x 3 columns]

The unqiue values in the target variable are 

In [4]:
news["Category"].unique()

array(['business', 'tech', 'politics', 'sport', 'entertainment'],
      dtype=object)

In [5]:
news["Text"][9]

'fockers fuel festive film chart comedy meet the fockers topped the festive box office in north america  setting a new record for christmas day.  the sequel took $44.7m (£23.2m) between 24 and 26 december  according to studio estimates. it took $19.1m (£9.9m) on christmas day alone  the highest takings on that day in box office history. meet the fockers is the sequel to ben stiller comedy meet the parents  also starring robert de niro  blythe danner  dustin hoffman and barbra streisand. despite the success of meet the fockers  takings were down 26.5% on 2003 s figures - which was blamed on christmas falling over a weekend this year.   when christmas falls on a weekend  it s bad for business   said paul dergarabedian  president of exhibitor relations  which compiles box office statistics. the weekend s top 12 films took an estimated $121.9m (£63.3m)  compared with $165.8m (£86.1m) last year  when the third lord of the rings film dominated the box office. meet the fockers knocked last we

In [6]:
news["Category"][9]

'entertainment'

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
vector=CountVectorizer(stop_words="english")

In [9]:
BOW= vector.fit_transform(news["Text"])

In [10]:
BOW

<1490x24456 sparse matrix of type '<class 'numpy.int64'>'
	with 213866 stored elements in Compressed Sparse Row format>

In [11]:
type(BOW)

scipy.sparse.csr.csr_matrix

In [12]:
BOW.shape

(1490, 24456)

In [22]:
len(vector.vocabulary_)

24456

Split the dataset into X and Y

In [15]:
x=pd.DataFrame(BOW.toarray(), columns=vector.get_feature_names_out())

In [16]:
y=news["Category"]

We have to do the label encoding for the target variable in order to proceed for modelling 

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
# initialize LabelEncoder
lencod = LabelEncoder()
# fit_transform() converts the text to numbers
news['Category'] = lencod.fit_transform(news['Category'])

In [19]:
y=news['Category']

In [20]:
y

0       0
1       0
2       0
3       4
4       0
       ..
1485    1
1486    1
1487    0
1488    4
1489    4
Name: Category, Length: 1490, dtype: int64

Splitting the dataset into train and test 

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 42)

In [23]:
X_train

00  000  0001  000bn  000m  000th  001  001and  001st  0051  ...  \
179    0    0     0      0     0      0    0       0      0     0  ...   
1439   0    0     0      0     0      0    0       0      0     0  ...   
1237   0    0     0      0     0      0    0       0      0     0  ...   
841    0    0     0      0     0      0    0       0      0     0  ...   
1462   0    0     0      0     0      0    0       0      0     0  ...   
...   ..  ...   ...    ...   ...    ...  ...     ...    ...   ...  ...   
1130   0    0     0      0     0      0    0       0      0     0  ...   
1294   0    0     0      0     0      0    0       0      0     0  ...   
860    0    1     0      0     0      0    0       0      0     0  ...   
1459   0    2     0      0     0      0    0       0      0     0  ...   
1126   0    0     0      0     0      0    0       0      0     0  ...   

      zonealarm  zones  zoom  zooms  zooropa  zorro  zuluaga  zurich  zutons  \
179           0      0     0      0        0      0        0       0       0   
1439          0      0     0      0        0      0        0       0       0   
1237          0      0     0      0        0      0        0       0       0   
841           0      0     0      0        0      0        0       0       0   
1462          0      0     0      0        0      0        0       0       0   
...         ...    ...   ...    ...      ...    ...      ...     ...     ...   
1130          0      0     0      0        0      0        0       0       0   
1294          0      0     0      0        0      0        0       0       0   
860           0      0     0      0        0      0        0       0       0   
1459          0      0     0      0        0      0        0       0       0   
1126          0      0     0      0        0      0        0       0       0   

      zvonareva  
179           0  
1439          0  
1237          0  
841           0  
1462          0  
...         ...  
1130          0  
1294          0  
860           0  
1459          0  
1126          0  

[1117 rows x 24456 columns]

Now we will do the Modelling using different models and find out which one gives the best results

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report

1.Logistic Regression

In [25]:
log_model=LogisticRegression()
log_model.fit(X_train,y_train)

y_predict=log_model.predict(X_test)

In [26]:
print("Results from logistic regression are as below")
log_result = classification_report(y_predict,y_test,output_dict=True)
log_result = pd.DataFrame(log_result).transpose()
log_result.style.background_gradient(cmap="BuPu")

Results from logistic regression are as below


In [31]:
print("Confusion Matrix of Logistic Regression \n" ,confusion_matrix(y_predict,y_test))

Confusion Matrix of Logistic Regression 
 [[89  1  1  0  1]
 [ 0 62  1  0  2]
 [ 1  0 68  0  2]
 [ 0  0  1 81  1]
 [ 2  0  0  0 60]]


2.DECISION TREE

In [27]:
DT = DecisionTreeClassifier()
DT.fit(X_train, y_train)
y_pred2 = DT.predict(X_test)

In [28]:
print("Results from Decision Tree are as below")
DT_result = classification_report(y_pred2,y_test,output_dict=True)
DT_result = pd.DataFrame(DT_result).transpose()
DT_result.style.background_gradient(cmap="BuPu")

Results from Decision Tree are as below


In [32]:
print("Confusion Matrix of Decision Tree \n" ,confusion_matrix(y_pred2,y_test))

Confusion Matrix of Decision Tree 
 [[63  3  4  2  5]
 [ 2 50  4  1  8]
 [12  4 57  3  2]
 [ 8  2  1 75  2]
 [ 7  4  5  0 49]]


3.Random Forest

In [29]:
RF = RandomForestClassifier()
RF.fit(X_train,y_train) 
y_pred3 = RF.predict(X_test)

In [30]:
print("Results from Random Forest are as below")
RF_result = classification_report(y_pred3,y_test,output_dict=True)
RF_result = pd.DataFrame(RF_result).transpose()
RF_result.style.background_gradient(cmap="BuPu")

Results from Random Forest are as below


In [33]:
print("Confusion Matrix of Random Forest \n" ,confusion_matrix(y_pred3,y_test))

Confusion Matrix of Random Forest 
 [[90  0  2  0  2]
 [ 0 60  0  0  0]
 [ 1  0 69  0  0]
 [ 0  2  0 81  1]
 [ 1  1  0  0 63]]


4.Gradient boosting

In [34]:
GB = GradientBoostingClassifier()
model = GB.fit(X_train,y_train)
y_pred4 = model.predict(X_test)

In [35]:
print("Results from Gradient Boosting are as below")
GB_result = classification_report(y_pred4,y_test,output_dict=True)
GB_result = pd.DataFrame(GB_result).transpose()
GB_result.style.background_gradient(cmap="BuPu")

Results from Gradient Boosting are as below


In [36]:
print("Confusion Matrix of Gradient boosting \n" ,confusion_matrix(y_pred4,y_test))

Confusion Matrix of Gradient boosting 
 [[86  2  2  0  2]
 [ 0 59  0  0  3]
 [ 3  0 69  0  0]
 [ 1  1  0 81  0]
 [ 2  1  0  0 61]]


5.Xtreme Gradient Boosting

In [37]:
xgb= XGBClassifier()
xgb_model = xgb.fit(X_train,y_train)
y_pred5 = xgb_model.predict(X_test)

In [38]:
print("Results from Xtreme Gradient boosting are as below")
xgb_result = classification_report(y_pred5,y_test,output_dict=True)
xgb_result = pd.DataFrame(xgb_result).transpose()
xgb_result.style.background_gradient(cmap="BuPu")

Results from Xtreme Gradient boosting are as below


In [39]:
print("Confusion Matrix of XGB \n" ,confusion_matrix(y_pred5,y_test))

Confusion Matrix of XGB 
 [[86  3  1  0  3]
 [ 0 57  0  0  1]
 [ 2  0 70  0  0]
 [ 1  2  0 81  0]
 [ 3  1  0  0 62]]


6.Bagging Clasifier

In [40]:
BC=BaggingClassifier()
BC_model=BC.fit(X_train , y_train)
y_pred8=BC_model.predict(X_test)

In [41]:
print("Results from Bagging classifier are as below")
BC_result = classification_report(y_pred8,y_test,output_dict=True)
BC_result = pd.DataFrame(BC_result).transpose()
BC_result.style.background_gradient(cmap="BuPu")

Results from Bagging classifier are as below


In [42]:
print("Confusion Matrix of Bagging classifier  \n" ,confusion_matrix(y_pred8,y_test))

Confusion Matrix of Bagging classifier  
 [[77  4  2  1  8]
 [ 1 56  2  0  3]
 [ 4  0 65  0  0]
 [ 9  2  1 80  3]
 [ 1  1  1  0 52]]


7.Navies Bayers

In [43]:
from sklearn.naive_bayes import MultinomialNB

NB = MultinomialNB()
NB_model=NB.fit(X_train, y_train)
y_pred9=NB_model.predict(X_test)

In [44]:
print("Results from Naives bayers classifier are as below")
NB_result = classification_report(y_pred9,y_test,output_dict=True)
NB_result = pd.DataFrame(NB_result).transpose()
NB_result.style.background_gradient(cmap="BuPu")

Results from Naives bayers classifier are as below


In [45]:
print("Confusion Matrix of Naives bayers classifier  \n" ,confusion_matrix(y_pred9,y_test))

Confusion Matrix of Naives bayers classifier  
 [[89  0  3  0  0]
 [ 0 63  0  0  0]
 [ 1  0 68  0  2]
 [ 0  0  0 81  0]
 [ 2  0  0  0 64]]


In [47]:
dfc =pd.concat([log_result["f1-score"], DT_result["f1-score"],RF_result["f1-score"],GB_result["f1-score"], xgb_result["f1-score"],BC_result["f1-score"],NB_result["f1-score"]],axis=1)
df2 = dfc.set_axis(["log_result","DT_result","RF_result","GB_result", "xgb_result","BC_result","NB_result"], axis=1, inplace=False)
df2

log_result  DT_result  RF_result  GB_result  xgb_result  \
0               0.967391   0.745562   0.967742   0.934783    0.929730   
1               0.968750   0.781250   0.975610   0.944000    0.942149   
2               0.957746   0.765101   0.978723   0.965035    0.979021   
3               0.987805   0.887574   0.981818   0.987805    0.981818   
4               0.937500   0.748092   0.961832   0.938462    0.939394   
accuracy        0.965147   0.788204   0.973190   0.954424    0.954424   
macro avg       0.963839   0.785516   0.973145   0.954017    0.954422   
weighted avg    0.965366   0.789812   0.973209   0.954584    0.954616   

              BC_result  NB_result  
0              0.836957   0.967391  
1              0.896000   1.000000  
2              0.928571   0.957746  
3              0.909091   1.000000  
4              0.859504   0.969697  
accuracy       0.884718   0.978552  
macro avg      0.886025   0.978967  
weighted avg   0.885415   0.978552

In [48]:
df2.loc[["macro avg","accuracy"]].transpose().sort_values(by="macro avg",ascending=False).style.background_gradient(cmap="RdPu")

Here we can see that the Naives bayers Algorithm has the best F1 score and Accuracy when compared with the other models 
Second best is for the random forest 